// GitHub Actions workflows are generated by zio-sbt-ci, do not edit .github/workflows/*.yml by hand.
// After changing this file run `sbt ciGenerateGithubWorkflow` and commit the result.
// Unlike build.sbt, this file is NOT produced by sbtgen.

import zio.sbt.ZioSbtCiPlugin._
import zio.sbt.githubactions.{ActionRef, Condition, Job, Step, Strategy}

ThisBuild / ciEnabledBranches     := Seq("develop")
ThisBuild / ciTargetJavaVersions  := Seq("17", "21")
ThisBuild / ciJvmOptions          := Seq(
  "-Xmx4000M",
  "-XX:ReservedCodeCacheSize=384M",
  "-XX:NonProfiledCodeHeapSize=256M",
  "-XX:MaxMetaspaceSize=1024M"
)

// Bot workflows we don't want: dependency updates are handled elsewhere (.scala-steward.conf is kept as is)
ThisBuild / ciEnableScalaSteward  := false
ThisBuild / ciEnableReleaseDrafter := false

// No `docs` sbt project lives in this build (it is injected from .mdl/resources/zio-docs.sbt when docs are published),
// and README.md is maintained by hand.
ThisBuild / ciCheckWebsiteBuildProcess := Seq.empty[Step]
ThisBuild / ciUpdateReadmeJobs         := Seq.empty[Job]

// The test matrix already compiles all platforms, including Scala Native which needs clang
ThisBuild / ciBuildJobs := Seq.empty[Job]

val installNativeToolchain = Step.SingleStep(
  name = "Install clang (Scala Native)",
  run = Some("sudo apt-get update && sudo apt-get install -y clang libunwind-dev")
)

ThisBuild / ciLintJobs := Seq(
  Job(
    id = "lint",
    name = "Lint",
    jobTimeout = Some(30),
    steps = Seq(
      Checkout.value,
      SetupJava(ciDefaultJavaVersion.value),
      SetupSBT,
      CacheDependencies,
      Step.SingleStep(name = "Setup Coursier", uses = Some(ActionRef("coursier/setup-action@v1"))),
      Step.SingleStep(
        name = "Check sbtgen output is up to date",
        run = Some("bash sbtgen.sc --js --native && git diff --exit-code")
      ),
      Step.SingleStep(
        name = "Check GitHub workflows are up to date",
        run = Some("sbt -batch ciCheckGithubWorkflow")
      )
    )
  )
)

ThisBuild / ciTestJobs := Seq(
  Job(
    id = "test",
    name = "Test",
    jobTimeout = Some(90),
    strategy = Some(
      Strategy(
        matrix = Map(
          "java"  -> ciTargetJavaVersions.value.toList,
          "scala" -> List("2.12", "2.13", "3")
        ),
        failFast = false
      )
    ),
    steps = Seq(
      Checkout.value,
      SetupJava("${{ matrix.java }}"),
      SetupSBT,
      CacheDependencies,
      installNativeToolchain,
      Step.SingleStep(
        name = "Test",
        run = Some(
          "sbt -batch " +
            "\"++ ${{ matrix.scala }} clean\" " +
            "\"++ ${{ matrix.scala }} Test/compile\" " +
            "\"++ ${{ matrix.scala }} test\" " +
            "\"++ ${{ matrix.scala }} mimaReportBinaryIssues\""
        )
      )
    )
  )
)

// Publishing keeps the existing flow (secrets.tar.enc + `+publishSigned`/`sonaRelease`):
// `sbt ci-release` needs sbt-ci-release + sbt-dynver, which do not fit the static version.sbt.
ThisBuild / ciReleaseJobs := Seq(
  Job(
    id = "release",
    name = "Release",
    need = ciReleaseApprovalJobs.value,
    jobTimeout = Some(60),
    condition = Some(
      Condition.Expression("github.event_name == 'release'") ||
        Condition.Expression("github.event_name == 'workflow_dispatch'") ||
        Condition.Expression("github.ref == 'refs/heads/develop'")
    ),
    steps = Seq(
      Checkout.value,
      SetupJava(ciDefaultJavaVersion.value),
      SetupSBT,
      CacheDependencies,
      installNativeToolchain,
      Step.SingleStep(
        name = "Publish to Sonatype",
        env = Map(
          "OPENSSL_IV"        -> "${{ secrets.OPENSSL_IV }}",
          "OPENSSL_KEY"       -> "${{ secrets.OPENSSL_KEY }}",
          "SONATYPE_USERNAME" -> "${{ secrets.SONATYPE_USERNAME }}",
          "SONATYPE_PASSWORD" -> "${{ secrets.SONATYPE_PASSWORD }}"
        ),
        run = Some(
          """|if [ -z "$OPENSSL_KEY" ] || [ -z "$OPENSSL_IV" ] || [ -z "$SONATYPE_USERNAME" ] || [ -z "$SONATYPE_PASSWORD" ]; then
             |  echo "Secrets are not available, skipping publish"
             |  exit 0
             |fi
             |if [[ "$GITHUB_REF" != refs/tags/v* && "$GITHUB_REF" != refs/heads/develop ]]; then
             |  echo "Publishing not allowed for $GITHUB_REF"
             |  exit 0
             |fi
             |openssl aes-256-cbc -K "${OPENSSL_KEY}" -iv "${OPENSSL_IV}" -in secrets.tar.enc -out secrets.tar -d
             |tar xvf secrets.tar
             |ln -s .secrets/local.sbt local.sbt
             |rm ./.secrets/credentials.sonatype-nexus.properties
             |printf "%s\n" "realm=Sonatype Nexus Repository Manager" "host=central.sonatype.com" "user=${SONATYPE_USERNAME}" "password=${SONATYPE_PASSWORD}" > ./.secrets/credentials.sonatype-nexus.properties
             |if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
             |  sbt -batch "show credentials" "+clean" "+Test/compile" "+publishSigned" "sonaRelease"
             |else
             |  sbt -batch "show credentials" "+clean" "+Test/compile" "+publishSigned"
             |fi
             |""".stripMargin
        )
      )
    )
  )
)

// Docs are published to npm through the zio-docs.sbt resource, there is no `docs` project in build.sbt
ThisBuild / ciPostReleaseJobs := {
  val releaseDocs = Job(
    id = "release-docs",
    name = "Release Docs",
    need = Seq("release"),
    jobTimeout = Some(30),
    condition = Some(
      Condition.Expression("github.event_name == 'release'") ||
        Condition.Expression("github.event_name == 'workflow_dispatch'")
    ),
    permissions = Map("contents" -> "read", "id-token" -> "write"),
    steps = Seq(
      Checkout.value,
      SetupJava(ciDefaultJavaVersion.value),
      SetupSBT,
      CacheDependencies,
      SetupNodeJs,
      Step.SingleStep(
        name = "Publish Docs to NPM Registry",
        run = Some(
          """|cp .mdl/resources/zio-docs.sbt zio-docs.sbt
             |awk '/<!--- docs:start --->/,/<!--- docs:end --->/' README.md >> docs/index.md
             |sed -i '/<!--- docs:start --->/d' docs/index.md
             |sed -i '/<!--- docs:end --->/d' docs/index.md
             |sbt -batch docs/publishToNpm
             |""".stripMargin
        )
      )
    )
  )
  releaseDocs +: postReleaseJobs.value.filter(_.id == "notify-docs-release")
}
