load("//rules:multiplatform.bzl", "scala_multiplatform_library", "scala_multiplatform_test")

scala_multiplatform_library(
    name = "izumi-reflect",
    srcs_root = "src/main",
    deps = [
        "//izumi-reflect/izumi-reflect-thirdparty-boopickle-shaded",
    ],
    visibility = ["//visibility:public"],
)

scala_multiplatform_test(
    name = "izumi-reflect-test",
    srcs_root = "src/test",
    lib_deps = [
        ":izumi-reflect",
        "//izumi-reflect/izumi-reflect-thirdparty-boopickle-shaded",
    ],
)
